name: $(Date:yyyyMMdd).$(Rev:.r)
trigger:
  - master
pr: none
jobs:
  - job: PrepareAppRelease
    variables:
      TAGS: '$(Build.SourceVersion)'
    steps:
      # Install Node dependencies
      - script: yarn add @octokit/rest --ignore-scripts
        displayName: 'Install NPM dependencies'

      - script: node tools/pipelines/scripts/set-last-merged-pr-commit-sha.js $(GITHUB_TOKEN)
        displayName: 'Set last merged pr commit SHA'

      - script: mkdir $(System.ArtifactsDirectory)/monorepopackage
        displayName: CreateDownloadOutputDirectory

      - task: DownloadBuildArtifacts@0
        displayName: 'Download Build Artifacts'
        inputs:
          buildType: specific
          project: '1da6e168-7f4d-4310-a107-b027ada4151a'
          pipeline: 5
          tags: '$(LAST_PR_SHA)'
          downloadType: single
          artifactName: drop
          downloadPath: '$(System.ArtifactsDirectory)/monorepopackage'

      - task: ExtractFiles@1
        inputs:
          archiveFilePatterns: '$(System.ArtifactsDirectory)/monorepopackage/drop/*.zip'
          destinationFolder: $(System.DefaultWorkingDirectory)/dist
          cleanDestinationFolder: true

      - task: PowerShell@2
        displayName: Read and tag affected apps in artifact
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          GITHUB_TOKEN: $(GithubToken)
        inputs:
          targetType: 'filePath'
          filePath: 'tools/pipelines/scripts/read-and-tag-affected-apps-in-artifact.ps1'
          pwsh: true

      - template: templates/publish-artifacts.yml
